// WS wire protocol shared by plugin <-> relay <-> mcp-server.
// Channel ID is per-session shared secret per D-009A mitigation 10 — 128-bit random
// generated by MCP server, displayed in plugin UI for human-eyes-only transfer.

export interface JoinMessage {
  readonly type: 'join';
  readonly channelId: string;
  readonly role: 'plugin' | 'mcp';
}

export interface JoinAckMessage {
  readonly type: 'join_ack';
  readonly channelId: string;
  readonly peerConnected: boolean;
}

export interface JoinErrorMessage {
  readonly type: 'join_error';
  readonly reason: 'invalid_channel' | 'channel_full' | 'role_taken';
}

export interface PingMessage {
  readonly type: 'ping';
  readonly ts: number;
}

export interface PongMessage {
  readonly type: 'pong';
  readonly ts: number;
}

export interface RequestMessage {
  readonly type: 'request';
  readonly id: string;
  readonly method: string;
  readonly params: Readonly<Record<string, unknown>>;
}

export interface ResponseMessage {
  readonly type: 'response';
  readonly id: string;
  readonly ok: boolean;
  readonly result?: unknown;
  readonly error?: { readonly code: string; readonly message: string };
}

export interface ProgressMessage {
  readonly type: 'progress';
  readonly id: string;
  readonly step: string;
  readonly fraction?: number;
}

export type WireMessage =
  | JoinMessage
  | JoinAckMessage
  | JoinErrorMessage
  | PingMessage
  | PongMessage
  | RequestMessage
  | ResponseMessage
  | ProgressMessage;

export type PluginRequestMethod =
  | 'get_document_info'
  | 'get_selection'
  | 'get_node_info'
  | 'get_nodes_info'
  | 'read_my_design'
  | 'get_local_components'
  | 'get_annotations'
  | 'get_styles'
  | 'get_instance_overrides'
  | 'scan_text_nodes'
  | 'scan_nodes_by_types'
  | 'get_reactions'
  | 'get_code_mapping';

// M1 read tools allowlist per D-008. Used by mcp-server at tool-registration time
// and by tools/list regression test (acceptance gate G4).
export const M1_READ_TOOLS: ReadonlyArray<PluginRequestMethod> = [
  'get_document_info',
  'get_selection',
  'get_node_info',
  'get_nodes_info',
  'read_my_design',
  'get_local_components',
  'get_annotations',
  'get_styles',
  'get_instance_overrides',
  'scan_text_nodes',
  'scan_nodes_by_types',
  'get_reactions',
  'get_code_mapping',
];
